import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from "axios"
import { useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  // console.log(props)
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState();
  console.log("data",data)
  useEffect(() => {
    // const hi = async () => {
    //   try {
    //     setLoading(true)
    //     const { data } = await axios.get("https://jsonplaceholder.typicode.com/photos");
    //     setData(data)
    //     setLoading(false);
    //   } catch (error) {
        
    //   }
    // }
    // hi()
     setLoading(true);
   
     setData(props.data1);
     setLoading(false);
    
   
  },[loading])
  if (!data || loading) {
    return <h1 style={{fontSize:"50px",textAlign:"center"}}>Fetching...</h1>
  }
  return (
    <>
      <Head>
        <title>Asikur Blog Website</title>
        <meta name="description" content="Generated by Asikur Blog Website" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Data Count:{data.length}</h1>
      <div style={{display:"flex",flexWrap:'wrap'}}>
        {data.map((d) => (
          <div className="card" key={d.id}>
            <div>
              <h3>{d.title}</h3>
            </div>
            <div>
              <img src={d.url} alt={d.title} />
            </div>
          </div>
        ))}
      </div>
    </>
  );
}
export async function getServerSideProps() {
  const { data } = await axios.get("https://jsonplaceholder.typicode.com/photos")
  const data1 = await data;
  return {
    props: {
      data1
    }
  }
}